[package]
name = "day-2-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.7.3"
regex = "1.10.2"
strum = { version = "0.25", features = ["derive"] }